
# Lista de nomes ou nomeros de telefone a serem pesquisados
# IMPORTANTE: O nome deve ser nao ambiguo pois ele retornara o primeiro resultado

lista_de_usuarios = [
'Débora Costa','Tiffany Costa', 'Magda Costa'
# 'Agropecuária Pai & Filho',
# 'Ailton Exame De Vista',
# 'Alesio Mecânico',
# 'Alexandra Cliente',
# 'Alexandre Pintor',
# 'Alexsandra Secretaria Escola',
# 'Alice 😝😝😝😝� ���😝😝',
# 'Amarildo Cliente',
# 'Amburguer Dom Oliveira',
# 'Amélia Maria Cliente',
# 'Ana Beatriz Cliente',
# 'Ana Caroline Cliente',
# 'Ana Cristina Cliente',
# 'Ana Lúcia Cliente',
# 'Ana Paula Cliente',
# 'Ana Paula Da Conceição Cliente',
# 'Ancelmo Cliente',
# 'Anderson Cliente',
# 'Anderson Frete Kombi',
# 'Andre Bigode',
# 'Andréa  Alves Cliente',
# 'Andrea Cliente',
# 'Andrea Martins Cliente',
# 'Andreia Cliente',
# 'Andreza Cliente',
# 'Angela Dicipuladora',
# 'Angela Exame De Vista',
# 'Angélica Exame De Vista',
# 'Angelita',
# 'Angu Da Ana',
# 'Aninha Faxina',
# 'Antônio C De Souza Cliente',
# 'Antônio Cliente',
# 'António Cliente 60',
# 'Armando C Cliente',
# 'Arnaldo Cliente',
# 'Arnaldo Pinheiro Cliente',
# 'Arraial Do Cabo Cliente',
# 'Art Gourmet Hambúrguer Artesanal',
# 'Atendente Botolink',
# 'Atendente Crefisa',
# 'Aula De Música'
]